### DISCUSSION TITLE
How can I exclude/filter specific MagicNumber issues in detekt.yml

### DISCUSSION THREAD

**Discussion by xetra11** [detekt/detekt#3283] [Q&A] [answered]
I am using Jetbrain's Compose for Desktop and the code structure there is a little bit odd and unconventional.
Given the following snippet:
```kotlin
Modifier.preferredSize(70.dp, 25.dp),
```
Detekt spits out a MagicNumber issue. I understand the problem - however I have no other way than going "magical" here.
I read in the `detekt.yml`. that there are some options to customize the behaviour.
This is my configuration therefore:

```yaml
  MagicNumber:
    active: false # inactive due my problem for now
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    ignoreNumbers: ['-1', '0', '1', '2']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
```

I found that `ignoreNamedArgument = true` might help but it does not work on the following:

```kotlin
Modifier.preferredSize(width = 70.dp, height = 25.dp)
```

So my question is how can I exclude the above numbers arguments that are plenty in my codebase?

(First Discussion Question :partying_face: )
