### DISCUSSION TITLE
Rethink the documentation rules

### DISCUSSION THREAD

**Discussion by BraisGabin** [detekt/detekt#4472] [Ideas]
Right now we have a bunch of rules related with `Kdoc` and some of them overlap a bit or there are some ones that seems that will do something but they don't because there is another rule that does its.

For that reason I think that we should rethink how do we want to keep those.

I can think of these rules (don't care about the names, they are terrible):

```yaml
UndocumentedPublic: # This rule only checks that there is kdoc, that's it! For it is fine if it's empty
  checkClass: true
  checkMethods: true
  checkProperties: true
  checkTopLevelFunctions: true
  checkTopLevelProperties: true
UndocumentedInternal: # Same but internal
  checkClass: true
  checkMethods: true
  checkProperties: true
  checkTopLevelFunctions: true
  checkTopLevelProperties: true
KdocClass: # If a class has Kdoc it checks that it's correct
  forceDescritpion: true
  forceParams: true
  forceTypeParams: true
  forceProperties: true
  forceContructor: true
  ...
KdocFunction: # Same but for functions
  forceDescritpion: true
  forceReturn: true
  forceParams: true
  forceThrowing: true
  ...
KdocProperty: # Same but for properties
  forceDescritpion: true
  ...
```

Maybe both `Undocumented*` could be merged in one. And all the `Kdoc*` would ensure that there is not `OutdatedDocumentation` so we don't need that rule. 

Related issues/PRs:
- #4436
- #4395
- #4462
- #3657
