### DISCUSSION TITLE
Review how global suppressions are made in default config.

### DISCUSSION THREAD

**Discussion by TWiStErRob** [detekt/detekt#4924] [Ideas]
## History

Some time ago the only way to suppress was a global `filters = '.*/test/.*'` or `--filter`.

Then came
```yml
test-pattern:
  active: true
  patterns:
    - '.*/test/.*'
    - '.*Test.kt'
  exclude-rule-sets:
    - 'some-rule-set'
  exclude-rules:
    - 'SomeRule'
```

Both of these were deprecated in favor of the new:
```
SomeRule:
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
```
which we could configure per rule giving us way more flexibility.

Now the latest addition is [suppressors](https://detekt.dev/docs/introduction/suppressors).
```yml
SomeRule:
  ignoreAnnotated:
    - 'javax.inject.Inject'
  ignoreFunction:
    - org.example.foo(kotlin.String)
```

## Proposal
With every new (more specific) way of suppression the exclusions were migrated to the new solution. I think there might be time for another look at the `**` excludes and use the new `ignore*` solutions where possible. This would help improve the quality of test code bases around the world.

## Background
https://github.com/detekt/detekt/issues/4921#issuecomment-1147184690 triggered me to write this recommendation.

## Some arguments
Tests are sometimes even more important to be readable than production code as they define what the production code should be doing. You can have golfed Kotlin code in production, if you have tests, you know what it is doing.

If test break, we should be able to see why it broke in order to know if it's the test or the production code broken, because these require different actions.

Based on this: helper functions, utility classes, fixture factories, etc. shouldn't have long names, or allow for wildcard imports, magic numbers, magic strings, etc.

Tests protect us making mistakes in the production code, but if they're internally broken, they don't help much; to bring an analogy: "one wouldn't want a shield with holes in it".
