### DISCUSSION TITLE
Standard SpringBootApplication class triggers UtilityClassWithPublicConstructor

### DISCUSSION THREAD

**Discussion by henrik242** [detekt/detekt#4989] [Q&A] [answered]
Is it possible to automatically exclude a `@SpringBootApplication` from the `UtilityClassWithPublicConstructor` rule? If not, maybe that could be a feature to implement?  It feels noisy to add a `@Suppress` here.
```
@SpringBootApplication
class ExternalApiApplication {
    companion object {
        fun main(args: Array<String>) {
            SpringApplication.run(ExternalApiApplication::class.java, *args)
        }
    }
}
```

**Comment by marschwar** [comment, marked as answer]
Please have a look at [the suppression documentation](https://detekt.dev/docs/introduction/suppressors). Without actually trying, I would assume that you could do:

```yaml
UtilityClassWithPublicConstructor:
  active: true
  ignoreAnnotated:
    - 'SpringBootApplication'
```
