### DISCUSSION TITLE
Custom Rules never called

### DISCUSSION THREAD

**Discussion by methob** [detekt/detekt#5047] [Q&A]
I tried many things to call the custom rule to be called but nothing works

My Rule: 

```
`class MyRule(config: Config= Config.empty) : Rule(config) {

    override val issue = Issue(
        "DatabaseImplLeak",
        Severity.CodeSmell,
        "Custom rule",
        Debt.FIVE_MINS,
    )

    override fun visitClass(kclass: KtClass) {
        super.visitClass(kclass)
        report(CodeSmell(issue, Entity.from(kclass), "Let me see if this hit here"))
    }
}`

```
```
`class MyRuleSetProvider : RuleSetProvider {
    override val ruleSetId: String = "clean-arch-rules"

    override fun instance(config: Config) = RuleSet(ruleSetId, listOf(MyRule(config)))
}`
```

config:

```
build:
    maxIssues: 0
    excludeCorrectable: false

config:
    validation: true
    # when writing own rules with new properties, exclude the property path e.g.: "my_rule_set,.*>.*>[my_property]"
    excludes: "clean-arch-rules,.*>.*"

processors:
    active: true
    exclude:
        - 'DetektProgressListener'

console-reports:
    active: true
    exclude:
        - 'ProjectStatisticsReport'
        - 'ComplexityReport'
        - 'NotificationReport'
        - 'FileBasedFindingsReport'

style:
    WildcardImport:
        active: false
        excludes: "**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"

clean-arch-rules:
  DatabaseImplLeak:
    active: true
```

i added this file: com.btg.pactual.banking.detekt_custom_rules.detekt.MyRuleSetProvider

my detekt version é 1.19.0

My Gradle version is 7.3.3
My kotlin version is 1.6.0
