### DISCUSSION TITLE
Custom indent size

### DISCUSSION THREAD

**Discussion by vytskalt** [detekt/detekt#5190] [Q&A] [answered]
How could I configure the indent size? I would like it to be 2 instead of 4.

**Comment by schalkms** [comment, marked as answer]
I'm not sure, what you exactly mean.
My best guess is to configure the `formatting` ruleset of detekt to handle the indent size as follows. Is this what you mean?

```yaml
formatting:
  active: true
  autoCorrect: true
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 4
```
