### DISCUSSION TITLE
Multiple ForbiddenImport patterns on different path

### DISCUSSION THREAD

**Discussion by JunDai** [detekt/detekt#5408] [Q&A] [answered]
**Description:**
Does/how does `ForbiddenImport` support multiple forbidden patterns on different paths for each?

**Context:**
Our project enables ForbiddenImport for certain lib/package classes for the entire project.
```yml
  ForbiddenImport:
    active: true
    imports:
      - 'com.xxx.yyy.util.*'
    forbiddenPatterns: ""
```
It's working fine for the entire project.

There is a new requirement that to block importing another set of classes within certain packages(design pattern)
```yml
  ForbiddenImport:
    active: true
    imports:
      - 'com.aaa.zzz.util.*'
    includes: "**/XZY*.kt"
    forbiddenPatterns: ""
```
This also works fine independently. But I can't find a way to have both import patterns work.
