### DISCUSSION TITLE
Migrating to new "libraries" ruleset and "libraries" property is not recognized

### DISCUSSION THREAD

**Discussion by lucaskivi** [detekt/detekt#5550] [Q&A] [answered]
I am attempting to migrate this:
```yml
style:
  active: true
  ...
  ForbiddenPublicDataClass:
    active: false
    ignorePackages: [ '*.internal', '*.internal.*' ]
  LibraryCodeMustSpecifyReturnType:
    active: true
  ...
```
to this
```yml
libraries:
  active: true
  ForbiddenPublicDataClass:
    active: false
  LibraryCodeMustSpecifyReturnType:
    active: true
    
style:
  ...
```

I have these dependencies:
```gradle
io.gitlab.arturbosch.detekt:detekt-formatting:1.22.0"
io.gitlab.arturbosch.detekt:detekt-rules-libraries:1.22.0"
```

and when I run detekt I get this error:

>  Property 'libraries' is misspelled or does not exist.

I thought I followed the migration guide well enough. What have a goofed up?
