### DISCUSSION TITLE
How to make the report fail if a certain rule is detected?

### DISCUSSION THREAD

**Discussion by alexban01** [detekt/detekt#6093] [General]
Hi, I'm adding detekt to a project and can't figure out how to make the analysis fail if it finds rules with severity "error". In the past I believe there was something called "FailFast" which I believe did what I want, but now it's removed.

<details>
  <summary>Full Github CI yml</summary>

```
name: Detekt

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  detekt:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Detekt
      id: setup_detekt
      uses: peter-murray/setup-detekt@v2
      with:
        detekt_version: '1.23.0-RC3'

    - name: Run Detekt
      run: detekt-cli
      with:
          args: --auto-correct --parallel --config detekt/config/detekt.yml
```
</details>
