### DISCUSSION TITLE
ForbiddenMethodCall rule doesn't raise lint errors for files under `src/test/kotlin` directory

### DISCUSSION THREAD

**Discussion by pr4bh4sh** [detekt/detekt#6485] [Q&A] [answered]
Hi,

I'm trying to use `ForbiddenMethodCall` to ban the use of the `error` method.

When I run `./gradlew detektMain` I get below result
```bash
> Task :detektMain FAILED
Property 'naming>BooleanPropertyNaming>ignoreOverridden' is deprecated. This configuration is ignored and will be removed in the future.
Property 'naming>FunctionNaming>ignoreOverridden' is deprecated. This configuration is ignored and will be removed in the future.
Property 'naming>FunctionParameterNaming>ignoreOverridden' is deprecated. This configuration is ignored and will be removed in the future.
Property 'naming>ConstructorParameterNaming>ignoreOverridden' is deprecated. This configuration is ignored and will be removed in the future.
Property 'naming>VariableNaming>ignoreOverridden' is deprecated. This configuration is ignored and will be removed in the future.
/<project_path>/src/main/kotlin/Main.kt:2:5: The method `kotlin.io.println` has been forbidden: println does not allow you to configure the output stream. Use a logger instead. [ForbiddenMethodCall]
/<project_path>/src/main/kotlin/Main.kt:7:5: The method `kotlin.error` has been forbidden: error() method hides Too generic exception [ForbiddenMethodCall]
```

The rule correctly raises the violation inside `src/main/kotlin` but not for `src/test/kotlin`.
Here's the rule config
```yaml
  ForbiddenMethodCall:
    active: true
    methods:
      - reason: 'print does not allow you to configure the output stream. Use a logger instead.'
        value: 'kotlin.io.print'
      - reason: 'println does not allow you to configure the output stream. Use a logger instead.'
        value: 'kotlin.io.println'
      - reason: 'error() method hides Too generic exception'
        value: 'kotlin.error'
```

I do not have any global exclusion for the `test` directory in `detekt.yml`
And gradle task is below
```kt
detekt {
//    debug = true
    toolVersion = detektVersion
    buildUponDefaultConfig = true // preconfigure defaults
    allRules = false // activate all available (even unstable) rules.
    baseline = file("$projectDir/config/detekt/baseline.xml") // a way of suppressing issues before introducing detekt
    autoCorrect = true
}
```
I'm using version `1.23.1` of detekt

Not sure what am I missing.
