### DISCUSSION TITLE
How to allow package name to use underscore (snake case)

### DISCUSSION THREAD

**Discussion by waffiqaziz** [detekt/detekt#7859] [Q&A] [answered]
Currently my config

```yml
  PackageNaming:
    active: false
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'
```
but still got message `Package name must not contain underscore [PackageName]`

I've tried https://stackoverflow.com/questions/45846555/detekt-snake-case-package but seems it was outdated,
