### DISCUSSION TITLE
ForbiddenMethodCall for global function

### DISCUSSION THREAD

**Discussion by victorpineda-jt** [detekt/detekt#8006] [Q&A] [answered]
I've been reading the doc about ForbiddenMethodCall: https://detekt.dev/docs/rules/style/#forbiddenmethodcall. It doesn't mentions global functions. I've tried different ways of declaring my global function in this rule but the check is not working. 

Example:

File GlobalFunctions.kt has a function called forbidden(). So I've tried:

```
  ForbiddenMethodCall:
    active: true
    methods:
      - 'com.mypackage.main.functions.GlobalFunctionsKt.forbidden'
      - 'com.mypackage.main.functions.GlobalFunctions.forbidden'
      - 'com.mypackage.main.functions.forbidden'
```

Unfortunately, none of these different ways of declaring the rule is working
