### ISSUE TITLE
Cannot enable autoCorrect only for single formatting rule

### ISSUE THREAD

**Issue by sschuberth** [detekt/detekt#1466]
## Expected Behavior

Using the configuration

```
formatting:
  autoCorrect: false
  ImportOrdering:
    autoCorrect: true
```

I'd expect `autoCorrect` to be enabled, but *only* for fixes to import ordering.

## Observed Behavior

Nothing is auto-corrected when running the `detekt` Gradle task.

## Steps to Reproduce

Checkout branch *detekt-rc-13-bug* of https://github.com/heremaps/oss-review-toolkit and run `./gradlew detekt`. Compare to the output with

```
formatting:
  autoCorrect: true
  ImportOrdering:
    autoCorrect: true
```

to see there actually are imports that *should* get fixed.

## Your Environment

* Version of detekt used: 1.0.0-RC13 (with `buildUponDefaultConfig = true`)
* Version of Gradle used (if applicable): 5.2.1
* Operating System and version: Windows 10
* Link to your project (if it's a public repository): https://github.com/heremaps/oss-review-toolkit/tree/detekt-rc-13-bug

**Comment by arturbosch** [comment]
I would argue this is intended behaviour. The more "top level" the autoCorrect is, the more does it turn on/off. When setting `active: false` on rule set level all rules get turned off. In your case enable the rule set and disable all rules expect the `ImportOrdering`

**Comment by sschuberth** [comment]
> I would argue this is intended behaviour.

I was fearing so 😉 This makes enabling of auto-correction for only a single / few formatting rules really cumbersome as you have to duplicate all formatting rules in order to disable `autoCorrect` for all other rules. That's esp. inconvenient as new rules appear, as then you'd have to update your config to also disable `autoCorrect` for these.

I was more thinking of it as a class hierarchy: The deeper nested a setting is, the more specialized it is, and as such it should override more generic settings.

The other use-case is that a user wants to have a convenient way to toggle auto-correct for all formatting rules at once. That could still be achieved by implementing the following behavior:

```
# Only top-level autoCorrect specified without any more specific formatting checks.
# If true, enabled autoCorrect for all formatting checks.
# If false, disables auto-formatting for all formatting checks.
formatting:
  autoCorrect: true|false
```

```
# Top-level autoCorrect enabled but a more specific formatting check disabled.
# This should enable auto-correct for all rules except ImportOrdering.
formatting:
  autoCorrect: true
  ImportOrdering:
    autoCorrect: false
```

```
# Top-level autoCorrect disabled but a more specific formatting check enabled.
# This should disable auto-correct for all rules except ImportOrdering.
formatting:
  autoCorrect: false
  ImportOrdering:
    autoCorrect: true
```
