### ISSUE TITLE
Non deterministic output. False positives on Indentation rule

### ISSUE THREAD

**Issue by hick209** [detekt/detekt#1633]
It looks like KtLint sometimes does not pick up indentation rules

## Expected Behavior
When running an analysis on a file more than once, the output should be the same if the file contents have not changed.

## Observed Behavior
Sometimes it outputs cleanly, no issues, 0 debt
![image](https://user-images.githubusercontent.com/927983/56624061-f4c85380-65eb-11e9-8655-9ae2c2879f78.png)

Every now and then (and it's not at all rare) if you run the analysis again without touching the file, it will output a whole bunch of Indentation errors.
![image](https://user-images.githubusercontent.com/927983/56624118-54befa00-65ec-11e9-86ed-f984102747c2.png)

## Steps to Reproduce
Create a configuration file with indentation `!= 4`, for example
```
autoCorrect: false

processors:
  active: false

output-reports:
  active: false

console-reports:
  active: true
  exclude:
  - 'ProjectStatisticsReport'
  - 'ComplexityReport'
  - 'NotificationReport'
  #  - 'FindingsReport'
  - 'BuildFailureReport'

formatting:
  active: true
  android: true
  autoCorrect: true
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 2
    continuationIndentSize: 4
  ParameterListWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
```

Test in a file that is compliant to the rules, like:
```
class EmptyBlocks {
  class EmptyClass {}

  fun exceptionHandling() {
    try {
    } finally {
    }
  }
}
```

Make sure you're adding the formatting plugin, for example, I ran the following commands:
```
./gradlew detekt-cli:shadowJar detekt-formatting:jar
java -jar detekt-cli/build/libs/detekt-cli-1.0.0-RC14-all.jar -c linter-config.yml -p detekt-formatting/build/libs/detekt-formatting-1.0.0-RC14.jar -i EmptyBlocks.kt
```

## Context
Making sure the output is deterministic and there are no false positives on Indentation issues.

## Your Environment
* Version of detekt used: 1.0.0.RC14 (tested on master as well)
* Version of Gradle used (if applicable): N/A
* Operating System and version: macOS
* Link to your project (if it's a public repository): N/A
