### ISSUE TITLE
Treat config property deprecations as errors

### ISSUE THREAD

**Issue by arturbosch** [detekt/detekt#2545]
## Expected Behavior
Implement an option to fail the build if any deprecated properties are used:

```yaml
config:
  validation: true
  warningsAsErrors: true
  excludes: ...
```

## Current Behavior
New behavior treats them as warnings which do not fail the build.

## Context
Old behavior treated them as errors which was considered a bug due to updating the detekt version should not unexpectedly break the build - #2523
