### ISSUE TITLE
ClassNaming rule treating Kotlin syntax ` as part of class name

### ISSUE THREAD

**Issue by hqzxzwb** [detekt/detekt#2656]
## Expected Behavior
ClassNaming rule should only check class name and should not check syntax \`

## Observed Behavior
ClassNaming rule treating Kotlin syntax \` as part of class name

## Steps to Reproduce
```Kotlin
class `$Test$`
```
The above code is warned about a ClassNaming issue with default config 
```
  ClassNaming:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/*.Test.kt', '**/*.Spec.kt', '**/*.Spek.kt']
    classPattern: '[A-Z$][a-zA-Z0-9$]*'
```
When I change the classPattern to ``[`A-Z$][`a-zA-Z0-9$]*``, the warning is gone.
This means detekt is treating the syntax ` as part of class name, which is probably not intended.

## Context
Class names with $ in it should pass the test, otherwise you would not write it to the default pattern. But it's not possible to have such a class name without the \` syntax.

## Your Environment

* Version of detekt used: 1.8.0
* Version of Gradle used (if applicable): 5.6.4
* Operating System and version: macOS Catalina
* Link to your project (if it's a public repository):
