### ISSUE TITLE
Add reasons in ForbiddenMethodCall & ForbiddenImport

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#3501]
## Expected Behavior
When detekt reports that a call or an import is forbidden it tell my why it is forbidden.

## Current Behavior
Right now detekt just say that it is forbidden so we a new person in the project doesn't know what to do.

## Context

Some coworkers ask me some times "Why is this forbidden?" And I need to explain them. That never bother me but after reading this in: https://saket.me/great-teams-merge-fast/ I realised that this explanation should be done by detekt.

**Comment by BraisGabin** [comment]
I imagine that we will need to change the configuration. Probably we should add a new one and maybe deprecate the old one.

Right now:
```yml
  ForbiddenImport:
    active: true
    imports:
      - 'org.mockito.*'
      - 'kotlinx.android.synthetic.*'
```

Proposal:
```yml
  ForbiddenImport:
    active: true
    imports:
      - import: 'org.mockito.*'
        reason: 'Use `com.nhaarman.mockitokotlin2` instead'
      - import: 'kotlinx.android.synthetic.*'
        reason: 'Use ViewBinding instead'
```

I don't like to much the proposal, any idea is more than welcome.

**Comment by cortinico** [comment]
> I imagine that we will need to change the configuration. Probably we should add a new one and maybe deprecate the old one.

Do we have other rules where this pattern could become useful? I suppose we have some scenarios where you want to either:
- Provide a more meaningful message to a developer
- Instantiate the same rule twice but with distinct purpose (as you presented in the example).

**Comment by BraisGabin** [comment]
Probably. For example the naming rules. You can have different regex for different use cases: "standard", "test", "dsl", etc.

But about the forbidden rules... Does it have sense to create an instance for each reason? If you forbid something you have to have a reason so I think that all of them could be in the same rule.

**Comment by cortinico** [comment]
> Does it have sense to create an instance for each reason?

I was more thinking at scenarios where you might want to re-instantiate the same rule but with different configs (say for different areas of your codebase 🤔 )

**Comment by BraisGabin** [comment]
Yes, yes, and that's what I mean with:

> Probably. For example the naming rules. You can have different regex for different use cases: "standard", "test", "dsl", etc.

You can have different configuration for your dsl files and other for test files.

**Comment by cortinico** [comment]
This is a really easy task for someone that wants to contribute to detekt. You can replicate what was done in #4126 to the `ForbiddenMethodCall` & `ForbiddenImport` rule (at least to allow a custom top level message).

**Comment by BraisGabin** [comment]
@marschwar I'm looking at this and I don't know exactly how to face it, maybe you can help me. I would like to support something like this:

```yaml
  ForbiddenImport:
    imports:
      - 'org.mockito.*'
      - import: 'kotlinx.android.synthetic.*'
        reason: 'Use ViewBinding instead'
      - import: 'foo.*'
```

The type of the list provided by `config` should be `List<Any>` and then in the transformation I would take care of transform that. Something like this:

```kotlin
    @Configuration("imports which should not be used")
    private val imports: List<ImportEntry> by config(emptyList<Any>()) { list ->
        list.distinct().map {
            when (it) {
                is String -> ImportEntry(it.simplePatternToRegex(), null)
                is Map<*, *> ->ImportEntry((it["import"]!! as String).simplePatternToRegex(), it["reason"] as String?)
                else -> error("Unknown type: $it")
            }
        }
    }

    data class ImportEntry(val regex: Regex, val reason: String?)
```

But right now we just support `List<String>` from `by config`. Anything else raises an exception. The key code is this one:

https://github.com/detekt/detekt/blob/08eac68caa24ced140cc017d4de3b258a470232b/detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/ConfigProperty.kt#L111-L130

**Comment by marschwar** [comment]
I think this is a dead end. We need to find a way to make this more generic. I was thinking along the lines of
```yaml
ForbiddenImport: 
  imports: 
    # I think mixing lists of strings and lists of maps does not necessarily have to be supported.
    # The user should pick one format per rule
    - org.mockito.*
    - 
      value: kotlinx.android.synthetic.*
      reason: "Use ViewBinding instead"
    - 
      value: foo.*
```
and (horrible name)
```kotlin
data class ConfiguredValue(val value: String, val reason: String?)
// ...
@Configuration("imports which should not be used")
private val imports: List<ConfiguredValue> by config(emptyList<ConfiguredValue>())
```
The mapping to `List<ConfiguredValue>` or `List<String>`could then be done in the delegate so this could be reused for all rules that need to support a list of values with individual reasoning.
I have not yet tried to implement this tbh. That is just a wild guess. If you think this would help and it could be a viable solution I can look into it further.

**Comment by BraisGabin** [comment]
I was thinking about allowing `List<Any>` but that would be impossible to document properly...

I like your idea! `value/reason` have sense for multiple rules so it would be great to support it out of the box.

> ```yaml
>     # I think mixing lists of strings and lists of maps does not necessarily have to be supported.
>     # The user should pick one format per rule
> ```

I'm not sure if it would be difficult to support. If it isn't that difficult I think that it would be good to support both. Because if you don't want to write a reason the `value: ` provides no value.

**Comment by marschwar** [comment]
> Because if you don't want to write a reason the value: provides no value.

I agree. I was talking about supporting 

```yaml
ForbiddenImport: 
  imports: 
    - org.mockito.*
    - kotlinx.android.synthetic.*
```
and 

```yaml
ForbiddenImport: 
  imports: 
    - 
      value: kotlinx.android.synthetic.*
      reason: "Use ViewBinding instead"
    - 
      value: foo.*
```
 But not

```yaml
ForbiddenImport: 
  imports: 
    - org.mockito.*
    - 
      value: kotlinx.android.synthetic.*
      reason: "Use ViewBinding instead"
```
