### ISSUE TITLE
ForbiddenComment should allow patterns

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#3508]
Following up on https://github.com/detekt/detekt/issues/959, the resolution of that is not powerful enough / complicates things.

## Context
We have the following configuration:
```yaml
  ForbiddenComment:
    values: ['REVIEW', 'STOPSHIP']
```
and I got this message flagged by Detekt:
```kotlin
// to express in the preview that it's not a normal TextView.
```
the only workaround I found is this
```yaml
  ForbiddenComment:
    values: ['REVIEW', 'STOPSHIP']
    # Allow "preview", "FireView", "DoReView" to occur in comments.
    # So only `// REVIEW explanation` will be flagged.
    # See https://github.com/detekt/detekt/issues/3508
    allowedPatterns: '(?<!^)(review|Review|reView|ReView)'
```

## Expected Behavior of the rule
```kotlin
// REVIEW foo -> flag
// review foo -> flag
// foo review -> allow
// preview -> allow
```
To do this I want to be able to say [`^(?i)REVIEW\b`](https://regex101.com/r/NioVGu/3) (as in case insensitive, starts with the letters "review" and it's not followed by word characters), instead of the current behavior which is https://regex101.com/r/NioVGu/2/
