### ISSUE TITLE
Autocorrects but also shows errors for the autocorrected issues

### ISSUE THREAD

**Issue by mortenholmgaard** [detekt/detekt#3834]
## Expected Behavior
When linting error could be autocorrected the should not show up as errors.

## Observed Behavior
When we run detekt by building the app (see setup below) it correctly autocorrects the linting issues, but they still shows up as errors! So you just have to rerun the build, but it is very annoying and inefficient that you have to do that.

## Steps to Reproduce
**detekt.gradle:**
```
apply plugin: "io.gitlab.arturbosch.detekt"

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:$detekt_version")
}

detekt {
    autoCorrect = true
    toolVersion = "$detekt_version"
    allRules = true
    buildUponDefaultConfig = true
    ignoreFailures = false
    config.setFrom( files("$rootDir/detekt.yml"))
}
```

**build.gradle (project):**
```
allprojects {
    apply from: "$rootDir/detekt.gradle"
    repositories {
       ...
    }
}
```

**build.gradle (module):**
```
tasks.whenTaskAdded { task ->
    if (task.name == 'compileXxxDevelopmentSources'
        || task.name == 'compileXxxStageSources'
        || task.name == 'compileXxxProdTestSources'
        || task.name == 'compileXxxProdSources') {
        task.dependsOn tasks.detekt
        task.mustRunAfter tasks.detekt
    }
}
```

## Context
Whenever we build the project it automatically runs detekt before compiling.

detekt.yml (not sure it is that relavant though)
```
potential-bugs:
    UnreachableCode:
        active: false
    ImplicitDefaultLocale:
        active: false
style:
    MagicNumber:
        active: false
    MaxLineLength:
        maxLineLength: 180
    WildcardImport:
        active: false
    UnusedPrivateMember:
        active: false
    ReturnCount:
        active: false
    ThrowsCount:
        active: false
    LoopWithTooManyJumpStatements:
        active: false
    UnnecessaryAbstractClass:
        active: false
formatting:
    MaximumLineLength:
        maxLineLength: 180
    PackageName:
        active: false
    NoWildcardImports:
        active: false
    ParameterListWrapping:
        active: false
naming:
    PackageNaming:
        active: false
exceptions:
    TooGenericExceptionThrown:
        active: false
    TooGenericExceptionCaught:
        active: false
    SwallowedException:
        active: false
empty-blocks:
    EmptyFunctionBlock:
        active: false
complexity:
    LongParameterList:
        active: false
    TooManyFunctions:
        active: false
    ComplexCondition:
        active: false
```

## Your Environment
* Version of detekt used: 1.16.0
* Version of Gradle used (if applicable): Gradle 6.7.1 and AGP 4.2.1
* Operating System and version: Windows 10 20H2
