### ISSUE TITLE
ThrowsCount config excludeGuardClauses misspelled or does not exist

### ISSUE THREAD

**Issue by eygraber** [detekt/detekt#3854]
Using detekt 1.17.1

```
ThrowsCount:
    active: true
    max: 3
    excludeGuardClauses: true

Run failed with 1 invalid config property.
        - Property 'style>ThrowsCount>excludeGuardClauses' is misspelled or does not exist.
```
