### ISSUE TITLE
Indentation incorrect for multiline expression in an assignment after the declaration that contains a null coalesce operator

### ISSUE THREAD

**Issue by eygraber** [detekt/detekt#3863]
Using Detekt 1.17.1. Not sure if this is part of the ongoing indentation issues with KtLint.

```
fun test() {
  val a: String = ""

  val someTest: Int?

  someTest =
    a
      .toIntOrNull()
      ?: 1
}
```

The Indentation rule is triggered by the third to last and second to last lines, and auto correct changes it to:

```
fun test() {
  val a: String = ""

  val someTest: Int?

  someTest =
    a
    .toIntOrNull()
    ?: 1
}
```

It seems like it's caused by a combination of the `val` (or `var`) not being on the same line as the assignment together with the null  coalescing operator.

```
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 2
    continuationIndentSize: 4
```
