### ISSUE TITLE
ReturnCount excludeGuardClauses doesn't seem to be working

### ISSUE THREAD

**Issue by eygraber** [detekt/detekt#3873]
Given the following code, I expect to not get a warning about ReturnCount, but I do:

```
  private fun String.parseSecrets(): JsonPublicKey {
    val topLevelElement = try {
      json.parseToJsonElement(this)
    }
    catch(t: Throwable) {
      return JsonPublicKey.Error("An error occurred while parsing json - ${t.message}")
    }

    val secretsJson = topLevelElement as? JsonObject
      ?: return JsonPublicKey.Error("expected a JsonObject but received ${topLevelElement.javaClass.simpleName}")

    val primitive = secretsJson["_public_key"]
      ?: return JsonPublicKey.Error("public key not present in EJSON file")

    val keyString = primitive.runCatching {
      jsonPrimitive.contentOrNull
    }.getOrNull() ?: return JsonPublicKey.Error("public key has invalid format")

    return runCatching {
      JsonPublicKey.Success(secretsJson, keyString.toPublicKey().getOrThrow())
    }.getOrElse {
      JsonPublicKey.Error(it.message ?: "no message")
    }
  }
```

And the config looks like:

```
  ReturnCount:
    active: true
    max: 2
    excludedFunctions: 'equals'
    excludeLabeled: false
    excludeReturnFromLambda: true
    excludeGuardClauses: true
```

## Your Environment
* Version of detekt used: 1.17.1
* Version of Gradle used (if applicable): 7.1
