### ISSUE TITLE
Rule configuration request: [LongMethod] Ignore based on annotations

### ISSUE THREAD

**Issue by robertsunday** [detekt/detekt#3887]
### Expected Behavior of the rule

```
LongMethod:
    active: true
    threshold: 20
    ignoreAnnotated: ['Composable']
```

### Context

We started recently to refactor our project to use Jetpack Compose. 
For `LongMethod` rule we have strict threshold set for 20 lines. It makes sense for regular Kotlin stuff. 

Jetpack `@Composable` methods tend to be quite big and we need to suppress detect in multiple places for such methods.

I would like to suggest adding a new configuration param for `LongMethod` rule to ignore checks based on annotation.

Please let me know your thoughts.
