### ISSUE TITLE
Ban certain library functions

### ISSUE THREAD

**Issue by alamothe** [detekt/detekt#3888]
Hello,

I would like to ban certain library functions (which are deemed unsafe or non-performant by our tech lead) from the codebase. Is this possible to do with detekt? 

Basically, a user provided list of functions (full qualified names) which would produce a warning if used.

**Comment by BraisGabin** [comment]
You have forbidden import and forbidden method (or function, I'm not sure) rules for those use cases.

**Comment by marschwar** [comment]
As mentioned by @BraisGabin you can use `ForbiddenMethodCall`:

```yaml
  ForbiddenMethodCall:
    active: true
    methods: ['kotlin.io.println', 'kotlin.io.print', 'your.library.function']
```
