### ISSUE TITLE
False positive on InvalidPackageDeclaration in Multiplatform project

### ISSUE THREAD

**Issue by eygraber** [detekt/detekt#3900]
Running `gradle :sample:app:detektMetadataMain` on https://github.com/eygraber/compose-color-picker results in 2 `InvalidPackageDeclaration` issues, but the package declaration seems fine to me.

**Comment by eygraber** [comment]
Also not sure if this is related or not, but it seems like the `excludes` property in the config isn't working for it. I have the following in the config:

```
  InvalidPackageDeclaration:
    active: true
    excludes: ['*.kts']
    rootPackage: ''
```

but if I run detekt on a `build.gradle.kts` file, it causes a `InvalidPackageDeclaration` report.
