### ISSUE TITLE
"Property 'comments>excludes' is misspelled or does not exist" with detekt 1.18.0

### ISSUE THREAD

**Issue by tomerarazy** [detekt/detekt#4038]
This is the relevant configuration:
```yml
comments:
  active: true
  excludes: ['**/test/**','**/androidTest/**','**/*.Test.kt','**/*task.Spec.kt','**/*.Spek.kt']
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  EndOfSentenceFormat:
    active: false
    endOfSentenceFormat: ([.?!][ \t\n\r\f<])|([.?!:]$)
  UndocumentedPublicClass:
    active: false
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: false
```

Kotlin 1.5.20
Detekt 1.18.0

It's  working fine with v1.17.1, I didn't see anything about it in the changelog.
