### ISSUE TITLE
[Feature Request] ImplicitLambdaParameter rules

### ISSUE THREAD

**Issue by QuinnBast** [detekt/detekt#4131]
Is there a rule that forces lambda parameters to be defined? My team would love to enforce something like this and completely require all lambda variables to be named.

```
var.map { it.value } // BAD!
var.map { namedVar -> namedVar.value } // Force a name!
```

I am also looking for a rule for lambda variable length requirements.

```
var.map { a -> a.value } // BAD!
var.map { moreSpecificName -> moreSpecificName.value } // Good.
```

_Originally posted by @QuinnBast in https://github.com/detekt/detekt/issues/3245#issuecomment-926899323_

**Comment by BraisGabin** [comment]
I think that we could change `MultilineLambdaItParameter` to fix the first point. But I think that it would be a Breaking change because we should rename it to `ImplicitItParameter`. And then have a flag (on by default) to "ignore one line lambdas".

I think that the second point should be handled by [VariableMinLength](https://detekt.github.io/detekt/naming.html#variableminlength). That or we should create one for `ParameterMinLength`.

**Comment by QuinnBast** [comment]
An alternative is to use the `VariableNaming` rule within lambdas. It would be possible to send it the following rule to error on variables named `it`:

```yaml
  VariableNaming:
    active: true
    excludes: "**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"
    variablePattern: '\b(?!it\b)([a-z][A-Za-z0-9]*)' # Error on variables named "it"
    privateVariablePattern: '\b(?!it\b)((_)?[a-z][A-Za-z0-9]*)' # Error on variables named "it"
    ignoreOverridden: true
```

This would make any variable named `it` fail the `VariableNaming` check. We just need to apply it to lambdas.
