### ISSUE TITLE
Support full qualified names for annotations in ignoreAnnotated

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4233]
## Expected Behavior
```yaml
  LateinitUsage:
    active: true
    ignoreAnnotated:
     - 'javax.inject.Inject'
```

Should ignore properties annotated with `@Inject` the same way as the old configuration:

```yaml
  LateinitUsage:
    active: true
    excludeAnnotatedProperties:
     - 'javax.inject.Inject'
```

## Observed Behavior
It doesn't

## Your Environment
* Version of detekt used: 1.19.0-RC1
