### ISSUE TITLE
ignoreAnnotated not respected on UnnecessaryAbstractClass

### ISSUE THREAD

**Issue by ZacSweers** [detekt/detekt#4356]
## Expected Behavior

After migrating to `ignoreAnnotated` per deprecation warning messages, it's no longer respecting the annotations we specify

Detekt 1.18.0
```yml
UnnecessaryAbstractClass:
  active: true
  excludeAnnotatedClasses: ['dagger.Module']
```

Warns

```
Property 'style>UnnecessaryAbstractClass>excludeAnnotatedClasses' is deprecated. Use `ignoreAnnotated` instead.
```

Detekt 1.19.0
```yml
UnnecessaryAbstractClass:
  active: true
  ignoreAnnotated: ['dagger.Module']
```

## Observed Behavior

It incorrectly warns about classes annotated with `dagger.Module`

## Steps to Reproduce

Here's an example module

```kotlin
@Module
abstract class CallsBaseModule {

  @Binds
  abstract fun CallPresenterImpl.provideCallPresenter(): CallContract.CallPresenter

  @Binds
  abstract fun CallServiceProviderImpl.bindCallServiceProvider(): CallServiceProvider
}
```

## Context

It is a regression

## Your Environment

* Version of detekt used: 1.19.0
* Version of Gradle used (if applicable): N/A
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: macOS 11
* Link to your project (if it's a public repository): N/A
