### ISSUE TITLE
ConstructorParameterNaming false positive

### ISSUE THREAD

**Issue by fluxxion82** [detekt/detekt#4360]
## Expected Behavior
New private constructor parameter should not be flagged.

## Observed Behavior
New private constructor parameter is being flagged as 'ConstructorParameterNaming' by detekt. If the parameter is made public, then it is not flagged by detekt despite having the same regex.

## Steps to Reproduce
Have project with baseline. Add new private constructor parameter.

## Context
Our ci is failing because detekt is making false positives.

## Your Environment
* Version of detekt used: 1.19.0-RC2 & 1.19.0
* Version of Gradle used (if applicable): 4.2.2
* Gradle scan link (add `--scan` option when running the gradle task): https://gradle.com/s/z4pjk2zouvb5i
* Operating System and version: MacOS Big Sur 11.6
* Link to your project (if it's a public repository): N/A

**Comment by BraisGabin** [comment]
Could you provide a snippet code to reproduce your issue? I think that I didn't understand completely your use case.

**Comment by fluxxion82** [comment]
So I have an existing project and we've setup detekt and everything. Most of the configs are the default. When we update a class and add a new private constructor parameter, then detekt is failing.

For example, we have an existing class:
```
class ExampleViewModel(
    private val paramOne: SomeObjectOne,
    private val paramTwo: SomeObjectTwo
) : BaseViewModel
```
Then we add a new private constructor parameter:

```
class ExampleViewModel(
    private val paramOne: SomeObjectOne,
    private val paramTwo: SomeObjectTwo,
    private val paramNew: NewObjectAdded
) : BaseViewModel
```
and this update will fail the detekt check. If we remove the `private` modifier, then it passes the detekt check. Here is our config for the constructor parameter naming:

```
  ConstructorParameterNaming:
    active: true
    excludes: ['**/test/**', '**/androidTest/**']
    parameterPattern: '[a-z][A-Za-z0-9]*'
    privateParameterPattern: '[A-Z$][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
    ignoreOverridden: true
```

Not sure if it matters, but I think these classes have entries (other than ConstructorParameterNaming) in the baseline.

Let me know if you need more info.
