### ISSUE TITLE
potential-bugs UselessPostfixExpression does not work in all cases

### ISSUE THREAD

**Issue by kepocnhh** [detekt/detekt#4617]
```kotlin
fun foo() {
    var i = 0
    i = i-- // work
    i = 1 + i++ // work
    i = i++ + 1 // work
    val i2 = i++ // does not work
    if (i2 == 1) { error("One!") }
    fun baz(): Int {
        var j = 0
        return j++ // work
    }
}
```

## Expected Behavior
The rule will work and the detekt will report an error in case of `val i2 = i++`.

## Observed Behavior
Detekt does not report an error in case of `val i2 = i++`.

## Steps to Reproduce
config:
```yml
build:
  maxIssues: 0

processors:
  active: false

console-reports:
  active: false

potential-bugs:
  active: true
  UselessPostfixExpression:
    active: true
```

## Context
Detekt reacts to the cases specified in the examples in the documentation. But it does not respond to the case specified above. Although even the ide suggests in this place.
![photo_2022-03-07_19-33-18](https://user-images.githubusercontent.com/6218886/157076728-97eec632-5473-4da0-b7c0-6711877b5115.jpg)

## Your Environment
detekt 1.20.0-RC1
Gradle 7.3
Kotlin 1.5.31
JVM 12.0.2 (Oracle Corporation 12.0.2+10)
OS: Linux 4.19.0-16-amd64
