### ISSUE TITLE
Allow to suppress properties same as functions

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4930]
## Context
I'm trying to configure Detekt using suppressors to allow `lateinit` for only specific names.
For example in all my tests, I use `private lateinit var sut: SystemUnderTest`, so I would like to allow `lateinit` usage on this specific name: `sut`.

## Current Behavior
I tried the following
```yml
potential-bugs:
  LateinitUsage:
    excludes: [ ] # Enforce this for production and test code.
    ignoreFunction:
      - 'sut'
      - 'getSut'
```
but it didn't work.

## Expected Behavior
A way to do this.

---

Note: next step I would like to also allow patterns `^mock.*` and `^fixt.*` which are also properties in test code. Although they're also annotated so I have a way.
