### ISSUE TITLE
Contradictory configuration of ForbiddenPublicDataClass

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4940]
## Context
This is more of a confusion than a bug, but it may be a bug. I was reading the default .yml and found what's in "observed". It looks like the rule is active, but it cannot run on any file?!

## Observed Behavior
```
  ForbiddenPublicDataClass:
    active: true
    excludes: ['**']
    ignorePackages:
      - '*.internal'
      - '*.internal.*'
```

## Expected Behavior
```
  ForbiddenPublicDataClass:
    active: true
    ignorePackages:
      - '*.internal'
      - '*.internal.*'
```
or
```
  ForbiddenPublicDataClass:
    active: false
    ignorePackages:
      - '*.internal'
      - '*.internal.*'
```

**Comment by TWiStErRob** [comment]
Oh, there's another two:
```
  LibraryCodeMustSpecifyReturnType:
    active: true
    excludes: ['**']
  LibraryEntitiesShouldNotBePublic:
    active: true
    excludes: ['**']
```

Starting to think this is intentional, just non-intuitive.
