### ISSUE TITLE
Support markdown report in Gradle plugin

### ISSUE THREAD

**Issue by 3flex** [detekt/detekt#4967]
## Expected Behavior
I can generate markdown output from the Gradle plugin (see #4858)

## Current Behavior
Support not yet added.

## Context
Built-in reports should all be easily enabled & configurable in Gradle.

**Comment by VitalyVPinchuk** [comment]
I'd like to work on this

**Comment by 3flex** [comment]
Closed by #4995

**Comment by 3flex** [comment]
Please raise a new issue if you think you have found a bug.

We will likely need a reproducer project to investigate. This was added 2 years ago and I'm not aware of any issues like it just not working at all.

**Comment by eddpascoal** [comment]
@3flex, 

Please ignore.. I had the configuration which was overwriting this..

```yml
  build:
    maxIssues: ...
    excludeCorrectable: false
  output-reports:
    active: true
    exclude:
     - 'TxtOutputReport' 
     - 'MdOutputReport'   <------ 
     - 'SarifOutputReport'
```
