### ISSUE TITLE
ForbiddenMethodCall with Kotlin getters as property

### ISSUE THREAD

**Issue by pinguinjkeke** [detekt/detekt#5015]
## Expected Behavior
Assume we have:
Java class:
```java
package com.hello;

class Hello {
    public String getHello() {
        return "hello";
    }
}
```
Detekt configuration:
```yaml
  ForbiddenMethodCall:
    active: true
    methods:
      - 'com.hello.Hello.getHello'
```
Somewhere in Kotlin:
```kotlin
val hello = Hello()
hello.hello // no error, but must be one
hello.getHello() // error, it's correct
```

## Observed Behavior
Kotlin property-getter not caught by Detekt

## Your Environment

* Version of detekt used: 1.20.0
* Operating System and version: Mac OS, Linux
