### ISSUE TITLE
UnusedPrivateMember not respecting ignoreAnnotated annotation 

### ISSUE THREAD

**Issue by leinardi** [detekt/detekt#5387]
## Expected Behavior

When I add a new annotation to the `ignoreAnnotated`, there should be no violations if such annotation is used on the member.

## Observed Behavior

A violation is thrown despite the member being annotated with a `ignoreAnnotated` annotation.

## Steps to Reproduce

```yml
  UnusedPrivateMember:
    active: true
    allowedNames: '(_|ignored|expected|serialVersionUID)'
    ignoreAnnotated: # Custom
      - 'DevicePreviews'
      - 'Preview'
```
The annotation:   https://github.com/android/nowinandroid/blob/main/core/ui/src/main/java/com/google/samples/apps/nowinandroid/core/ui/DevicePreviews.kt

Usage of the annotation:
```kotlin
@DevicePreviews
@Composable
private fun PreviewLogInScreen() {
    PreviewFeature {
        LogInScreen(State(false, "", ""), Channel<Effect>().receiveAsFlow()) {}
    }
}
```
Violation:  
```
 UnusedPrivateMember - [Private function `PreviewLogInScreen` is unused.]
```

## Context

Interestingly, the stock annotation `@Preview` is ignored correctly, it's just this new, custom annotation that is not ignored.

## Your Environment

* Version of detekt used: 1.21.0
* Version of Gradle used (if applicable): 7.5.1
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: Ubuntu 22.04
* Link to your project (if it's a public repository): Currently I don't have a public repository where the issue happens but, if needed, I can invest some time in creating one. Let me know
