### ISSUE TITLE
TrimMultilineRawString: ability to turn off for specific methods

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#5430]
## Expected Behavior of the rule
```yml
TrimMultilineRawString:
  ignores:
    - org.skyscreamer.jsonassert.JSONAssert.assertEquals(*: kotlin.String, *: kotlin.String, _: org.skyscreamer.jsonassert.JSONCompareMode)
    - io.ktor.client.engine.mock.MockUtilsKt.respond(_: io.ktor.client.enginemock.MockRequestHandleScope, *: java.lang.String, _: io.ktor.http.HttpStatusCode, _: io.ktor.http.Headers)
```
(Ideally with the ability to specify which parameter of a specific override is ignored / above `*` means importantly ignored, `_` means whatever.)

## Context
There are some use cases where the indentation does not matter, and it can be an outright performance bottleneck given a large enough scale (e.g. backend serialization tests). An example is this call:
```kotlin
JSONAssert.assertEquals(
	"""
		{
		  "id" : "${user.id}",
		  "email" : "${user.email}"
		}
	""",
	call.response.content,
	JSONCompareMode.STRICT
)
```
Notice that this is a library that compares JSON [semantically](http://jsonassert.skyscreamer.org/javadoc/org/skyscreamer/jsonassert/JSONCompareMode.html#STRICT) (after parsing it), so that the tests don't become flaky because of spaces and newlines and order.

**Comment by TWiStErRob** [comment]
## Workaround
... because I'm lucky that all these are straight in the test method body.
```yml
  TrimMultilineRawString:
    ignoreAnnotated:
      - 'org.junit.jupiter.api.Test'
```
