### ISSUE TITLE
Ignoring NewLineAtEndOfFile

### ISSUE THREAD

**Issue by Drjacky** [detekt/detekt#5464]
## Expected Behavior
To not receive `The file .../build.gradle.kts is not ending with a new line. [NewLineAtEndOfFile]`
while I have this in the yml config:
```yml
style:
  active: true
  .
  .
  .
  NewLineAtEndOfFile:
    active: false
```

## Observed Behavior
`The file .../build.gradle.kts is not ending with a new line. [NewLineAtEndOfFile]`

## Your Environment

* Version of detekt used: 1.22.0-RC2
* Version of Gradle used (if applicable): 7.5.1
* Operating System and version: macOS

**Comment by BraisGabin** [comment]
Is this a regression? Did it happen when updating detekt? Or does it happen on any version of detekt? If it happens on other versions of detekt too it seems like a missconfiguration, does the same happen with other rules?

**Comment by Drjacky** [comment]
I have the issue with the 1.19.0 before updating to the 1.22.0-RC2 as well.

Same issue with `MagicNumber`:
```yml
MagicNumber:
    active: false
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
    ignoreNumbers: [ '-1', '0', '1', '2' ]
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
```

Sample project: https://github.com/Drjacky/MVIModularizationTemplate  

- Versions: https://github.com/Drjacky/MVIModularizationTemplate/blob/master/buildSrc/src/main/kotlin/app/web/drjackycv/buildsrc/Depends.kt  

- YML: https://github.com/Drjacky/MVIModularizationTemplate/blob/master/config/detekt/detekt.yml
