### ISSUE TITLE
New Suppressor for callsites

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#5510]
## Expected Behavior
 * ability to suppress a specific function by name (all overloads) [example for this in Context below]
 * ability to suppress a specific function by name (specific overload)
 * ability to suppress a specific function specific argument (by name)
 * ability to suppress a specific function specific argument (by position/type) [example for this in Context below]

As a side-note: I would add this suppressor to the list of https://detekt.dev/docs/current/introduction/suppressors/ BEFORE it's implemented to gain visibility in advance and maybe a contributor.

## Current Behavior
Feature not available. Workaround would be to turn off the built-in rule, create a new rule that wraps the rule and call the rule conditionally, or post-process its findings, but this is tedious. Another alternative would be https://github.com/detekt/detekt/issues/4932.

## Context
There are some rules which are useful, except in certain cases where a known function is being called, where we would like to be able to "ignore" them.

Let's see an example: https://github.com/detekt/detekt/issues/5430
```yaml
TrimMultilineRawString:
  ignores:
    # These function calls receive JSON, but their formatting/indentation doesn't matter because they're only semantically processed (parsed).
    - org.skyscreamer.jsonassert.JSONAssert.assertEquals(*: kotlin.String, *: kotlin.String, _: org.skyscreamer.jsonassert.JSONCompareMode)
    - io.ktor.client.engine.mock.MockUtilsKt.respond(_: io.ktor.client.enginemock.MockRequestHandleScope, *: java.lang.String, _: io.ktor.http.HttpStatusCode, _: io.ktor.http.Headers)
```

Another example: https://github.com/detekt/detekt/discussions/4527
```yaml
SpreadOperator:
  ignores:
    # There's no other way to call this function when the migrations are already in a pre-gathered array.
    # https://developer.android.com/reference/kotlin/androidx/room/RoomDatabase.Builder#addMigrations(kotlin.Array)
    - androidx.room.RoomDatabase.Builder.addMigrations
```

## Known issues it would address:

- [ ] #5430
- [ ] #4527
