### ISSUE TITLE
ReturnCount JSON Schema is outdated

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#5588]
## Expected Behavior
https://json.schemastore.org/detekt.json

```json
        "ReturnCount": {
          "type": "object",
          "properties": {
            "active": {
              "type": "boolean"
            },
            "excludedFunctions": {
              "type": "some kind of array"
            },
            ...
          }
        },
```

## Observed Behavior
```json
        "ReturnCount": {
          "type": "object",
          "properties": {
            "active": {
              "type": "boolean"
            },
            "excludedFunctions": {
              "type": "string"
            },
            ...
          }
        },
```

## Steps to Reproduce
Edit detekt.yml in IDEA and add
```yml
  ReturnCount:
    max: 3
    excludedFunctions:
      # Ignore MenuProvider.onMenuItemSelected, Activity.onOptionsItemSelected,
      # and Fragment.onOptionsItemSelected, because they have a special structure for bug prevention.
      - 'onMenuItemSelected'
      - 'onOptionsItemSelected'
```

if you follow the schema you get:
> Property 'style>ReturnCount>excludedFunctions' should be a YAML array instead of a comma-separated String.

if you follow the warning you get:
> Schema validation: Incompatible types. Required: string. Actual: array.

There's no winning :)

## Context
My doc update in https://github.com/detekt/detekt/pull/5062 triggered https://github.com/detekt/detekt/issues/5063 which was fixed by https://github.com/detekt/detekt/pull/5081, but that made the schema on schemastore outdated. Would be solved by #4162

## Your Environment

* Version of detekt used: 1.22.0
