### ISSUE TITLE
Check for illegal usage of functions annotated with `@TestOnly` or `@VisibleForTesting`

### ISSUE THREAD

**Issue by mrclrchtr** [detekt/detekt#5643]
## Expected Behavior of the rule
Functions annotated with [@TestOnly](https://javadoc.io/doc/org.jetbrains/annotations/latest/org/jetbrains/annotations/TestOnly.html) (JetBrains) or [@VisibleForTesting](https://guava.dev/releases/snapshot/api/docs/com/google/common/annotations/VisibleForTesting.html) (Guava) should not be used in production code, but only in test code.

## Context
I think it's the same as: https://rules.sonarsource.com/java/RSPEC-5803?search=junit

**Comment by schalkms** [comment]
This is already possible with the help of the `ForbiddenAnnotation` rule.
You could configure it like this, for instance, no need for a separate rule IMHO.

```yml
ForbiddenAnnotation:
  active: true
  excludes: ['**/test/**', '**/*.Test.kt']
  annotations:
    - value: 'org.jetbrains.annotations.TestOnly'
       reason: 'should not be used in production code, but only in test code'
    - value: 'com.google.common.annotations.VisibleForTesting'
       reason: 'should not be used in production code, but only in test code'
```
