### ISSUE TITLE
`PathFilters` behavior doesn't match its docs

### ISSUE THREAD

**Issue by haluzpav** [detekt/detekt#5728]
## Expected Behavior
Having both `includes` and `excludes` on a rule config, both of the constraints should be applied.

## Observed Behavior
`excludes` is ignored when `includes` is there.

## Steps to Reproduce

(fabricated example)

```yml
naming:
  ConstructorParameterNaming:
    includes: ["**/model/**"]
    excludes: ["**/*Exception.kt"]
```

File: `project/src/main/java/com/example/model/CustomException.kt`

The rule `ConstructorParameterNaming` is applied to the file, even though it matches the `excludes` filter.

## Context

I have a custom rule (can't share) which I want to apply only on some files. Being able to use both `includes` and `excludes` would help, although I can get around it by using just one of them.

The possible mistake is at https://github.com/detekt/detekt/blob/main/detekt-api/src/main/kotlin/io/gitlab/arturbosch/detekt/api/internal/PathFilters.kt#L32. The kotlin docs of the function there match the expected behavior.

## Your Environment

* Version of detekt used: 1.22
