### ISSUE TITLE
Align the use of literals, regex and glob on the configuration

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#6075]
On detekt we have a lot of configurations. Some of them are strings. But depending on the rule we interpret that string as a literal, a regex or a glob. That's confusing!

I know that align all of them is nearly impossible but it would be nice to have some guideline. And now with 2.0 I think is a really good moment.

- Literals are the simplest but doesn't give too much flexibility.
- Regex are the opposite. Complex but great flexibility.
- And glob is the middle grown.

Also we even have rules that allow literals and regex.

An option could be to define a new type of configuration.

Here an example for `ForbiddenImports`
```yaml
imports:
  - 'this string is a literal' 
importsRegex:
  - '^this string is a regex$' 
importsGlob:
  - 'this string is a glob' 
```

Other option is to have only one key and allow to define the how that string should be interpreted. 

I'm not sure which is the correct solution here but I think that we should do something to align this.

**Comment by atulgpt** [comment]
I am for `Other option is to have only one key and allow to define the how that string should be interpreted.` as for the other option where we allow 3 different options, how will we decide the priority between those 3? Or will we allow more than one to be defined in a rule?

**Comment by BraisGabin** [comment]
My idea was to allow multiple of them to be defined. We would merge them. We can map all of them to `List<Regex>`.

**Comment by marschwar** [comment]
Since `ForbiddenImports` uses the `ValuesWithReason` already those two concepts should be combined somehow. How about:

```yaml
  ForbiddenImports:
    imports:
      - value: 'TypeA.*'
        reason: reason A
        format: regex
      - value: TypeB
```

or 

```yaml
  ForbiddenImports:
    imports:
      - value: 'regex:TypeA.*'
        reason: reason A
      - value: TypeB
```
