### ISSUE TITLE
New Rule: Enum entries for enums matching a configuration should be in alphabetical order

### ISSUE THREAD

**Issue by drawers** [detekt/detekt#6115]
Searched in issues and could not find this suggested previously.

## Expected Behavior of the rule
This rule defines a configuration:

```yaml
EnumEntriesAlphabeticalOrder:
  active: false
  includeAnnotated: ["com.example.annotations.Alphabetical"]
  includeInterfaces: ["com.example.interfaces.Alphabetical"]
  include: ["com.example.MyEnum"]
```
This configuration allows a project to mark enums that they wish to keep in alphabetical order. They can do this in the most generic way by specifying their own annotation (e.g., a `@Alphabetical` annotation within their own project). Detekt will scan the project and look for enums that have that annotation explicitly applied or applied through implementing an interface decorated with the annotation. It will report when these enums have entries that are not in alphabetical order.

Further options for configuration are listing FQN of interfaces that mark enums to be scanned. I am not sure about using regex or wildcard lists to configure this rule

#### With annotation in configuration

```yaml
EnumEntriesAlphabeticalOrder:
  active: true
  includeAnnotated: ["com.example.annotations.Alphabetical"]
```

```kotlin
import com.example.annotations.Alphabetical

@Alphabetical
enum class AnalyticsVariable { // non-compliant (explicitly annotated with configured annotation)
   USER_ID,
   ITEMS_IN_CART,   
}
```

```kotlin
import com.example.annotations.Alphabetical

@Alphabetical
enum class AnalyticsVariable { // compliant 
   ITEMS_IN_CART,
   USER_ID, 
}
```

```kotlin
import com.example.annotations.Alphabetical

@Alphabetical
interface Analytics

// non-compliant (implements interface decorated with @Alphabetical and entries out of order)
enum class AnalyticsVariable : Analytics {
   USER_ID,
   ITEMS_IN_CART,
}

// compliant
enum class AnalyticsVariable: Analytics {
   ITEMS_IN_CART,
   USER_ID
}
```

#### With interfaces
```yaml
EntriesAlphabeticalOrder:
  active: true
  includeInterfaces: ["com.example.interfaces.Alphabetical"]
```

```kotlin
interface Alphabetical
```

```kotlin
// non-compliant (implements interface in config)
enum class AnalyticsVariable : Alphabetical {
   USER_ID,
   ITEMS_IN_CART,
}

// compliant 
enum class AnalyticsVariable: Alphabetical {
   ITEMS_IN_CART,
   USER_ID, 
}
```

## Context
In large Android codebases, the file containing an enum can become chaotic. It's not often not clear for devs where to add their new constant - should it be at the end of the file (to maintain chronological order) or somewhere else? It's not right to say every enum should be in alphabetical order because there are some where the ordinal matters (e.g., an enum where we are using the enum `ordinal` or when we are parsing an Int into an enum). Keeping in alphabetical order allows quick scanning of a file to understand contents but it generates a lot of friction in PRs and it also generates a noisy diff when someone decides to reorder a chaotic enum file. It can also generate potential bugs when people sort in alphabetical order without considering whether this is appropriate

I have worked on codebases where keeping enums entries in alphabetical order was required of devs and we solved it by writing our own Android Lint rule similar to how this proposed rule works. I've also vaguely remember hearing about it in projects at Uber (a difference in style project between the Uber Eats and the Uber Taxi projects?).
