### ISSUE TITLE
Autoformatting moves object to the next line

### ISSUE THREAD

**Issue by nacyolsa** [detekt/detekt#6223]
## Expected Behavior
Autoformatting should not reformat below line to incorrect state
```
private val deferredMessageQueueSubscription = DeferredMessageQueueSubscription(uri = ServiceBusUri("deferredQueueTestUri"))
```

## Observed Behavior
Autoformatting moves `DeferredMessageQueueSubscription(uri = ServiceBusUri("deferredQueueTestUri"))` to the next line and as the results it looks like this:
```
    private val deferredMessageQueueSubscription = 
    DeferredMessageQueueSubscription(uri = ServiceBusUri("deferredQueueTestUri"))
```
I think it may be related to max line length limit but still I think it should not touch this but throw a warning instead.

Related to `PropertyWrapping`.

## Your Environment
* Version of detekt used: 1.23.0
* Operating System and version: Kotlin 1.8.21

**Comment by atulgpt** [comment]
Hi, @nacyolsa in my case autoformatting is working correctly like below
```
private val deferredMessageQueueSubscription = 
    DeferredMessageQueueSubscription(uri = ServiceBusUri("deferredQueueTestUri"))
```
with an indentation in the second line. 
Is wrong formatting happening consistently in your case?

**Comment by nacyolsa** [comment]
For me in both cases like below:

```
private val deferredMessageQueueSubscription =
DeferredMessageQueueSubscription(uri = ServiceBusUri("deferredQueueTestUri"))

class TestC {
    private val deferredMessageQueueSubscription =
    DeferredMessageQueueSubscription(uri = ServiceBusUri("deferredQueueTestUri"))
}
```
Formatting is incorrect.

>Is wrong formatting happening consistently in your case?

For this case always when I run Detekt.
I checked this also in smaller project and it didn't occur so it is connected to something else.

**Comment by atulgpt** [comment]
Hi, @nacyolsa can you also share your `detekt.yml`?

**Comment by nacyolsa** [comment]
@atulgpt Here you go:

```yaml
formatting:
    excludes: [ '**/build/**' ]
    MaximumLineLength:
        active: false
    NoBlankLineBeforeRbrace:
        active: false
    Indentation:
        active: false
    ArgumentListWrapping:
        active: false
    MultiLineIfElse:
        active: false
style:
    excludes: [ '**/build/**' ]
    MagicNumber:
        active: true
        excludes: [ '**/build.gradle.kts', '**/test/**', '**/build/**' ]
    MaxLineLength:
        maxLineLength: 180
        active: true
    ForbiddenComment:
        active: true
    RedundantHigherOrderMapUsage:
        active: false
    VarCouldBeVal:
        active: false
naming:
    excludes: [ '**/build/**' ]
    MemberNameEqualsClassName:
        active: true
        excludes: [ '**/buildSrc/**' ]
    InvalidPackageDeclaration:
        active: false
    NoNameShadowing:
        active: false
    TopLevelPropertyNaming:
        active: false
complexity:
    excludes: [ '**/build/**' ]
    LongParameterList:
        functionThreshold: 15
        excludes: ['**/test/**']
    TooManyFunctions:
        thresholdInFiles: 15
        thresholdInClasses: 15
coroutines:
    InjectDispatcher:
        active: false

ArrowRuleSet:
    NoEffectScopeBindableValueAsStatement:
        active: true
```
