### ISSUE TITLE
ForbiddenMethodCall does not trigger on default interface implementations

### ISSUE THREAD

**Issue by vatbub** [detekt/detekt#6474]
This bug is related to #4204

## Expected Behavior
Consider the following code:

```kotlin
import javafx.beans.property.SimpleObjectProperty

class DetektForbiddenMethodCallDefaultInterfaceDemo {
    val objectProperty = SimpleObjectProperty("Hello there")
    val mappedProperty = objectProperty.map { it.uppercase() }
}
```

With the following configuration, ForbiddenMethodCall should flag the call to `.map()`.

```yml
  ForbiddenMethodCall:
    active: true
    methods:
      - reason: 'The javafx-built in ObservableValue.map function handles null values in an unusual and in Kotlin undesired way. Use map2() instead.'
        value: 'javafx.beans.value.ObservableValue.map'
```

## Observed Behavior
The call is not flagged. However, the following configuration will flag the call:

```yml
  ForbiddenMethodCall:
    active: true
    methods:
      - reason: 'The javafx-built in ObservableValue.map function handles null values in an unusual and in Kotlin undesired way. Use map2() instead.'
        value: 'javafx.beans.value.ObservableValue.map'
      - reason: 'The javafx-built in ObservableValue.map function handles null values in an unusual and in Kotlin undesired way. Use map2() instead.'
        value: 'javafx.beans.property.SimpleObjectProperty.map'
```

It seems like this is the same bug as #4204 except with one difference: `SimpleObjectProperty` does not override `map`. Instead, the `ObservableValue` interface contains a default implementation, which apparently is not recognized by the patch that fixed #4204 .

Here are the relevant portions of source code for reference: [ObservableValue](https://github.com/openjdk/jfx/blob/eb7de72dafecbedc83c2215b6aed7432d4ec80f9/modules/javafx.base/src/main/java/javafx/beans/value/ObservableValue.java#L178) and [SimpleObjectProperty](https://github.com/openjdk/jfx/blob/eb7de72dafecbedc83c2215b6aed7432d4ec80f9/modules/javafx.base/src/main/java/javafx/beans/property/SimpleObjectProperty.java#L39)

## Steps to Reproduce
Create a project with the following dependency:

```xml
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-base</artifactId>
    <version>19.0.2.1</version>
</dependency>
```

Then paste the above code in the project and run detekt with type resolution enabled on that project.

## Your Environment
* Version of detekt used: 1.23.1
* Version of Gradle used (if applicable): N/A
* Gradle scan link (add `--scan` option when running the gradle task): N/A
* Operating System and version: Windows 10
* Link to your project (if it's a public repository): private
