### ISSUE TITLE
Allow exceptions for ForbiddenImport

### ISSUE THREAD

**Issue by vatbub** [detekt/detekt#6536]
## Expected Behavior of the rule
Consider the following config:

```yaml
  ForbiddenImport:
    active: true
    imports:
      - 'org.junit.jupiter.api.*'
```

This blocks all imports from the package `org.junit.jupiter.api`, which is almost what I want. There are some annotations in that package which are actually required and must be imported from that package (for example: `org.junit.jupiter.api.AfterAll`). Right now, I am just suppressing the ForbiddenImport rule in the files which need those annotations, but it would be better for ForbiddenImport to have a separate allow-list which allows imports that would otherwise be forbidden by `imports`.
