### ISSUE TITLE
Detekt fails for "excludes" Property 'bilahbilah>excludes' is misspelled or does not exist.

### ISSUE THREAD

**Issue by HamidSedghi** [detekt/detekt#6722]
## Observed Behavior
Upgrading Detekt to 1.23.3
Bitrise failes with below error:

* What went wrong:
Execution failed for task ':sonar'.
> Run failed with 8 invalid config properties.
  	- Property 'complexity>excludes' is misspelled or does not exist.
  	- Property 'coroutines>excludes' is misspelled or does not exist.
  	- Property 'empty-blocks>excludes' is misspelled or does not exist.
  	- Property 'exceptions>excludes' is misspelled or does not exist.
  	- Property 'naming>excludes' is misspelled or does not exist.
  	- Property 'performance>excludes' is misspelled or does not exist.
  	- Property 'potential-bugs>excludes' is misspelled or does not exist.
  	- Property 'style>excludes' is misspelled or does not exist.
It seems excludes are not accepted.

## Steps to Reproduce

`    excludes: ['**/legacy/**', '**/*.Test.kt', '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']`
 I have excludes for some random properties in my yaml file such as
 
 ```
comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false
    licenseTemplateFile: 'license.template'
    excludes: ['**/legacy/**', '**/*.Test.kt', '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
```

## Context
Detekt fails the Sonar will fail. If I remove excludes then all is good but I need to increate my baseline file to cover those issues in possible excluded folders.

## Your Environment
BitRise + Github
Detekt 1.23.3
Jacoco 0.8.11
Kotlin 1.8.22
Sonar 4.4.1.3373
