### ISSUE TITLE
Gradle Compiler Plugin - Exclude does not work at the ruleset level

### ISSUE THREAD

**Issue by mrclrchtr** [detekt/detekt#6958]
As already discussed here: https://github.com/detekt/detekt/discussions/6604

## Expected Behavior
```
naming:
  active: true
  excludes: [ '**/src/**' ]
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
```
Should exclude all files in "src".

## Observed Behavior
It is not excluded.

## Steps to Reproduce
I created a minimal example here: https://github.com/mrclrchtr/gradle-detekt-compiler-plugin-bug with the exclusion here https://github.com/mrclrchtr/gradle-detekt-compiler-plugin-bug/blob/7da17a8ed8e6e368a7049f9d8640ff2874d4b74e/config.yml#L16 and the failing build here: https://github.com/mrclrchtr/gradle-detekt-compiler-plugin-bug/actions/runs/7832556886/job/21371525166

## Context
I tried to exclude generated sources.

## Your Environment
* Version of detekt used: 1.23.5
* Version of Gradle used (if applicable): 8.5
* Gradle scan link (add `--scan` option when running the gradle task):
* Link to your project (if it's a public repository): https://github.com/mrclrchtr/gradle-detekt-compiler-plugin-bug
