### ISSUE TITLE
Detekt ignoring excludes after updating Kotlin version

### ISSUE THREAD

**Issue by zsperske** [detekt/detekt#6970]
## Expected Behavior
Detekt should respect excludes.

## Observed Behavior
I have a detekt.yml file with:

```
build:
  maxIssues: 0
  excludeCorrectable: false
  excludes: '**/generated/**'
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1
```

After updating from kotlin & KSP from 1.9.10 to 1.9.22, I am getting detekt violations on files such as:

`workspace/android/features/feature1/network/build/generated/ksp/main/SomeFile.kt Line detected, which is longer than the defined maximum line length in the code style. [MaxLineLength]
`

## Steps to Reproduce
I don't have one.

## Context
Trying to update our Compose version which requires a kotlin version update.

## Your Environment
* Version of detekt used: v1.23.5, also tried v1.23.1
* Version of Gradle used (if applicable): 8.3
* Operating System and version: OSX and on a linux CI machine.
