### ISSUE TITLE
StringTemplateIndent conflicts with MultilineRawStringIndentation

### ISSUE THREAD

**Issue by mrclrchtr** [detekt/detekt#7198]
## Expected Behavior
MultilineRawStringIndentation and StringTemplateIndent should work together.

## Observed Behavior
MultilineRawStringIndentation and StringTemplateIndent seems to conflict.

With fixed MultilineRawStringIndentation
![image](https://github.com/detekt/detekt/assets/16151098/62bf0621-28d6-45ef-8fef-14cd1e0f7110)

With fixed StringTemplateIndent
![image](https://github.com/detekt/detekt/assets/16151098/026b33f5-6352-4fb8-8c35-3f323e4653d0)

## Steps to Reproduce
MultilineRawStringIndentation
```yaml
  MultilineRawStringIndentation:
    active: true
    indentSize: 2
    trimmingMethods:
      - 'trimIndent'
      - 'trimMargin'
```
StringTemplateIndent
```yaml
  StringTemplateIndent:
    active: true
    autoCorrect: true
    indentSize: 2
```

```kotlin
    logger.info {
      """
        Postgres database login parameters:
        URL: ${container.jdbcUrl} 
        Username: ${container.username} 
        Password: ${container.password} 
      """.trimIndent()
    }
```

## Your Environment
* Version of detekt used: 2.4.0 (IntelliJ Plugin)
