### ISSUE TITLE
UnusedPrivateProperty does not detect unused property named "logger"

### ISSUE THREAD

**Issue by Chris-Goetz** [detekt/detekt#7222]
## Expected Behavior
detekt should find unused properties for which no exception is defined. 

## Observed Behavior
detekt does not find unused properties named "logger".

## Steps to Reproduce
![Screenshot from 2024-04-24 13-29-18](https://github.com/detekt/detekt/assets/141140288/80cdd1f6-098f-49c9-bc76-46f5f2865297)

## Context
The documentation statesthe default allowed values are: allowedNames (default: '_|ignored|expected|serialVersionUID') - "logger" is not listed here.
We also have no exceptions in our config for that rule defined:
```
---
build:
  weights:
    LongParameterList: 0
    TooManyFunctions: 0

complexity:
  excludes: ["**/test/**"]

formatting:
  MaximumLineLength:
    excludes: ["**/test/**"]
  NoWildcardImports:
    active: false
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true

naming:
  FunctionParameterNaming:
    excludes: ["**/test/**"]
  ClassNaming:
    excludes: ["**/test/**"]
  MemberNameEqualsClassName:
    active: false

style:
  MaxLineLength:
    excludes: ["**/test/**"]
  WildcardImport:
    active: false
  SerialVersionUIDInSerializableClass:
    active: false

config:
  validation: true

```

## Your Environment
* Version of detekt used: 1.23.5
* Version of Gradle used (if applicable):
------------------------------------------------------------
Gradle 8.6
------------------------------------------------------------
Build time:   2024-02-02 16:47:16 UTC
Revision:     d55c486870a0dc6f6278f53d21381396d0741c6e

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.10 (Private Build 17.0.10+7-Ubuntu-122.04.1)
OS:           Linux 6.5.0-28-generic amd64
