### ISSUE TITLE
autoCorrect not working without "buildUponDefaultConfig = true"

### ISSUE THREAD

**Issue by alexandre-thauvin** [detekt/detekt#7333]
## Expected Behavior
autoCorrect shall work without buildUponDefaultConfig

## Observed Behavior
autoCorrect doesn't work without buildUponDefaultConfig

## Steps to Reproduce
run **./gradlew detekt --auto-correct**

I think it's coming from my **detekt.yml** file but why is that?

I have checked the [default-detekt-config.yml](https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml) and I did not see anything that I would need in mine...

so why if I don't put "buildUponDefaultConfig = true" in the detekt closue it doesn't autoCorrect anything despite having autoCorrect in formatting section and even specifying in other rules?

**detekt.yml:**

```
build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true

console-reports:
  active: true

output-reports:
  active: true
  exclude:
    - 'MdOutputReport'
    - 'SarifOutputReport'
    - 'TxtOutputReport'

processors:
  active: true

comments:
  active: true

  DeprecatedBlockTag:
    active: true

complexity:
  active: true

  CognitiveComplexMethod:
    active: true
    threshold: 35

  ComplexCondition:
    active: true

  CyclomaticComplexMethod:
    active: true
    threshold: 35

  LargeClass:
    active: true

  LongMethod:
    active: true
    ignoreAnnotated: [ 'Composable', 'Parameters' ]

  LongParameterList:
    active: true
    constructorThreshold: 10
    ignoreDefaultParameters: true
    ignoreAnnotated: [ 'Composable' ]

  NestedBlockDepth:
    active: true

  StringLiteralDuplication:
    active: true
    ignoreAnnotated: [ 'Parameters', 'Test' ]

  TooManyFunctions:
    active: true
    thresholdInFiles: 99
    thresholdInClasses: 30
    thresholdInObjects: 20
    ignoreOverridden: true

coroutines:
  active: true

  GlobalCoroutineUsage:
    active: true

  InjectDispatcher:
    active: true

  RedundantSuspendModifier:
    active: true

  SleepInsteadOfDelay:
    active: true

  SuspendFunWithFlowReturnType:
    active: true

empty-blocks:
  active: true

  EmptyCatchBlock:
    active: true

  EmptyClassBlock:
    active: true

  EmptyDefaultConstructor:
    active: true

  EmptyDoWhileBlock:
    active: true

  EmptyElseBlock:
    active: true

  EmptyFinallyBlock:
    active: true

  EmptyForBlock:
    active: true

  EmptyFunctionBlock:
    active: true
    autoCorrect: true

  EmptyIfBlock:
    active: true

  EmptyInitBlock:
    active: true

  EmptyKtFile:
    active: true

  EmptySecondaryConstructor:
    active: true

  EmptyTryBlock:
    active: true

  EmptyWhenBlock:
    active: true

  EmptyWhileBlock:
    active: true

exceptions:
  active: true

  ExceptionRaisedInUnexpectedLocation:
    active: true

  InstanceOfCheckForException:
    active: true

  NotImplementedDeclaration:
    active: true

  ObjectExtendsThrowable:
    active: true

  PrintStackTrace:
    active: true

  RethrowCaughtException:
    active: true

  ReturnFromFinally:
    active: true

  ThrowingExceptionFromFinally:
    active: true

  ThrowingExceptionsWithoutMessageOrCause:
    active: true

  ThrowingNewInstanceOfSameException:
    active: true

  TooGenericExceptionCaught:
    active: true

  TooGenericExceptionThrown:
    active: true

formatting:
  active: true
  autoCorrect: true

  AnnotationOnSeparateLine:
    active: true

  AnnotationSpacing:
    active: true

  ArgumentListWrapping:
    active: true
    # make sure this is aligned to MaxLineLength
    maxLineLength: 145

  ChainWrapping:
    active: true

  ClassName:
    active: true

  CommentSpacing:
    active: true

  EnumEntryNameCase:
    active: true

  EnumWrapping:
    active: true

  Filename:
    active: true

  FinalNewline:
    active: true
    insertFinalNewLine: true

  FunKeywordSpacing:
    active: true

  FunctionReturnTypeSpacing:
    active: true

  FunctionSignature:
    active: true
    forceMultilineWhenParameterCountGreaterOrEqualThan: 2
    # make sure this is aligned to MaxLineLength
    maxLineLength: 145
    ignoreAnnotated: [ 'Composable' ]

  FunctionStartOfBodySpacing:
    active: true

  FunctionTypeReferenceSpacing:
    active: true

  IfElseBracing:
    active: true

  IfElseWrapping:
    active: true

  ImportOrdering:
    active: true

  Indentation:
    active: true

  ModifierListSpacing:
    active: true

  ModifierOrdering:
    active: true

  MultiLineIfElse:
    active: true

  NoBlankLineBeforeRbrace:
    active: true

  NoBlankLinesInChainedMethodCalls:
    active: true

  NoConsecutiveBlankLines:
    active: true

  NoEmptyClassBody:
    active: true

  NoEmptyFirstLineInClassBody:
    active: true

  NoEmptyFirstLineInMethodBlock:
    active: true

  NoLineBreakAfterElse:
    active: true

  NoLineBreakBeforeAssignment:
    active: true

  NoMultipleSpaces:
    active: true

  NoSemicolons:
    active: true

  NoTrailingSpaces:
    active: true

  NoUnitReturn:
    active: true

  NoUnusedImports:
    active: true

  NoWildcardImports:
    active: true

  NullableTypeSpacing:
    active: true

  ParameterListSpacing:
    active: true

  ParameterListWrapping:
    active: true
    # make sure this is aligned to MaxLineLength
    maxLineLength: 145

  ParameterWrapping:
    active: true

  SpacingAroundAngleBrackets:
    active: true

  SpacingAroundColon:
    active: true

  SpacingAroundComma:
    active: true

  SpacingAroundCurly:
    active: true

  SpacingAroundDot:
    active: true

  SpacingAroundDoubleColon:
    active: true

  SpacingAroundKeyword:
    active: true

  SpacingAroundOperators:
    active: true

  SpacingAroundParens:
    active: true

  SpacingAroundRangeOperator:
    active: true

  SpacingAroundUnaryOperator:
    active: true

  SpacingBetweenDeclarationsWithAnnotations:
    active: true

  SpacingBetweenDeclarationsWithComments:
    active: true

  SpacingBetweenFunctionNameAndOpeningParenthesis:
    active: true

  StringTemplate:
    active: true

  TrailingCommaOnCallSite:
    active: false
    useTrailingCommaOnCallSite: true

  TryCatchFinallySpacing:
    active: true

  TypeArgumentListSpacing:
    active: true

  TypeParameterListSpacing:
    active: true

  UnnecessaryParenthesesBeforeTrailingLambda:
    active: true

naming:
  active: true

  BooleanPropertyNaming:
    active: true
    allowedPattern: '^(is|has|are|can)'

  ClassNaming:
    active: true

  ConstructorParameterNaming:
    active: true

  EnumNaming:
    active: true

  FunctionNaming:
    active: true
    ignoreAnnotated: [ 'Composable', 'Test' ]

  FunctionParameterNaming:
    active: true

  InvalidPackageDeclaration:
    active: true

  LambdaParameterNaming:
    active: true

  MatchingDeclarationName:
    active: true

  MemberNameEqualsClassName:
    active: true

  NoNameShadowing:
    active: true

  NonBooleanPropertyPrefixedWithIs:
    active: true

  ObjectPropertyNaming:
    active: true

  PackageNaming:
    active: true

  TopLevelPropertyNaming:
    active: true

  VariableNaming:
    active: true

performance:
  active: true

  CouldBeSequence:
    active: true

  ForEachOnRange:
    active: true

  SpreadOperator:
    active: true

  UnnecessaryPartOfBinaryExpression:
    active: true

  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true

  AvoidReferentialEquality:
    active: true

  CastNullableToNonNullableType:
    active: true

  CastToNullableType:
    active: true

  Deprecation:
    active: true

  DontDowncastCollectionTypes:
    active: true

  DoubleMutabilityForCollection:
    active: true

  ElseCaseInsteadOfExhaustiveWhen:
    active: true

  EqualsAlwaysReturnsTrueOrFalse:
    active: true

  EqualsWithHashCodeExist:
    active: true

  ExplicitGarbageCollectionCall:
    active: true

  HasPlatformType:
    active: true

  IgnoredReturnValue:
    active: true

  ImplicitDefaultLocale:
    active: true

  ImplicitUnitReturnType:
    active: true

  InvalidRange:
    active: true

  IteratorHasNextCallsNextMethod:
    active: true

  IteratorNotThrowingNoSuchElementException:
    active: true

  LateinitUsage:
    active: true
    ignoreOnClassesPattern: '.*Test'

  MapGetWithNotNullAssertionOperator:
    active: true

  MissingPackageDeclaration:
    active: true

  NullCheckOnMutableProperty:
    active: true

  NullableToStringCall:
    active: true

  PropertyUsedBeforeDeclaration:
    active: true

  UnconditionalJumpStatementInLoop:
    active: true

  UnnecessaryNotNullCheck:
    active: true

  UnnecessaryNotNullOperator:
    active: true

  UnnecessarySafeCall:
    active: true

  UnreachableCatchBlock:
    active: true

  UnreachableCode:
    active: true

  UnsafeCallOnNullableType:
    active: true

  UnsafeCast:
    active: true

  UnusedUnaryOperator:
    active: true

  UselessPostfixExpression:
    active: true

  WrongEqualsTypeParameter:
    active: true

style:
  active: true

  AlsoCouldBeApply:
    active: true

  BracesOnIfStatements:
    active: true
    singleLine: never
    multiLine: always

  BracesOnWhenStatements:
    active: true
    singleLine: necessary
    multiLine: necessary

  CanBeNonNullable:
    active: true

  CascadingCallWrapping:
    active: true

  ClassOrdering:
    active: true

  CollapsibleIfStatements:
    active: true

  DestructuringDeclarationWithTooManyEntries:
    active: true

  DoubleNegativeLambda:
    active: true

  EqualsNullCall:
    active: true

  EqualsOnSignatureLine:
    active: true

  ExplicitCollectionElementAccessMethod:
    active: true

  ExplicitItLambdaParameter:
    active: true

  ForbiddenAnnotation:
    active: true

  ForbiddenVoid:
    active: true

  FunctionOnlyReturningConstant:
    active: true

  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 2

  MagicNumber:
    active: true
    ignoreAnnotated: [ 'Parameters', 'Test', 'Before' ]

  MandatoryBracesLoops:
    active: true

  MaxChainedCallsOnSameLine:
    active: true
    maxChainedCalls: 2

  # make sure this is aligned to ArgumentListWrapping, FunctionSignature
  MaxLineLength:
    active: true
    maxLineLength: 145

  MayBeConst:
    active: true

  ModifierOrder:
    active: true

  NestedClassesVisibility:
    active: true

  NewLineAtEndOfFile:
    active: true
    autoCorrect: true

  NullableBooleanCheck:
    active: true

  ObjectLiteralToLambda:
    active: true

  OptionalAbstractKeyword:
    active: true

  OptionalUnit:
    active: true

  PreferToOverPairSyntax:
    active: true

  ProtectedMemberInFinalClass:
    active: true

  RedundantExplicitType:
    active: true

  RedundantHigherOrderMapUsage:
    active: true

  RedundantVisibilityModifierRule:
    active: true

  ReturnCount:
    active: true
    max: 5

  SafeCast:
    active: true

  SerialVersionUIDInSerializableClass:
    active: true

  SpacingBetweenPackageAndImports:
    active: true

  ThrowsCount:
    active: true

  TrailingWhitespace:
    active: true

  UnderscoresInNumericLiterals:
    active: true

  UnnecessaryAbstractClass:
    active: true

  UnnecessaryAnnotationUseSiteTarget:
    active: true

  UnnecessaryApply:
    active: true

  UnnecessaryBackticks:
    active: true

  UnnecessaryBracesAroundTrailingLambda:
    active: true

  UnnecessaryFilter:
    active: true

  UnnecessaryInheritance:
    active: true

  UnnecessaryInnerClass:
    active: true

  UnnecessaryLet:
    active: true

  UnnecessaryParentheses:
    active: true

  UntilInsteadOfRangeTo:
    active: true

  UnusedImports:
    active: true

  UnusedParameter:
    active: true

  UnusedPrivateClass:
    active: true

  UnusedPrivateMember:
    active: true
    ignoreAnnotated: [ 'Preview' ]

  UnusedPrivateProperty:
    active: true

  UseAnyOrNoneInsteadOfFind:
    active: true

  UseArrayLiteralsInAnnotations:
    active: true

  UseCheckNotNull:
    active: true

  UseCheckOrError:
    active: true

  UseDataClass:
    active: true

  UseEmptyCounterpart:
    active: true

  UseIfEmptyOrIfBlank:
    active: true

  UseIsNullOrEmpty:
    active: true

  UseLet:
    active: true

  UseOrEmpty:
    active: true

  UseRequire:
    active: true

  UseRequireNotNull:
    active: true

  UseSumOfInsteadOfFlatMapSize:
    active: true

  UselessCallOnNotNull:
    active: true

  UtilityClassWithPublicConstructor:
    active: true

  VarCouldBeVal:
    active: true

  WildcardImport:
    active: true

```

**build.gradle (root):**

```
subprojects {
    apply plugin: 'io.gitlab.arturbosch.detekt'

    detekt {
        // buildUponDefaultConfig = true // I need to uncomment it in order the autoCorrect to work        
        config.setFrom('../config/detekt/detekt.yml')
        parallel = true
        autoCorrect = true
        source = files(
                "src/android/java",
                "src/huawei/java",
                "src/main/java",
                "src/androidTest/java",
                "src/test/java",
        )
    }

    dependencies {
        detektPlugins libs.detekt // detekt import
        detektPlugins "io.gitlab.arturbosch.detekt:detekt-formatting:1.23.6"
    }

    tasks.withType(Detekt).configureEach {
        reports {
            md.required.set(false)
            sarif.required.set(false)
            txt.required.set(false)
        }
    }
}
```

## Your Environment
* Version of detekt used:1.23.6
* Version of Gradle used (if applicable):8.7
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: macOS 14.5
* Link to your project (if it's a public repository):
