### ISSUE TITLE
Unable to setup `CoroutineLaunchedInTestWithoutRunTest` rule

### ISSUE THREAD

**Issue by piloudu** [detekt/detekt#7338]
## Expected Behavior
The following YAML configuration should enable the `CoroutineLaunchedInTestWithoutRunTest` rule:

```YAML
coroutines:
  active: true
  CoroutineLaunchedInTestWithoutRunTest:
    active: false
  # ...
```

## Observed Behavior
Enabling the `CoroutineLaunchedInTestWithoutRunTest` rule with the same YAML config as in here
https://github.com/detekt/detekt/blob/f8bf79b24baebd10fda01ffe2ef586cf8bc1fff1/detekt-core/src/main/resources/default-detekt-config.yml#L177

produces the following error:

```
Property 'coroutines>CoroutineLaunchedInTestWithoutRunTest' is misspelled or does not exist
```

The rule is pretty new

## Steps to Reproduce
Happens both on `v1.23.5` and `v1.23.6`

## Your Environment
Detekt dependencies in use in `libs.versions.toml`:

```TOML
[versions]
detekt="1.23.6"

[libraries]
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
```
