### ISSUE TITLE
Excluding Sarif output report via yaml config file does not work

### ISSUE THREAD

**Issue by WebTiger89** [detekt/detekt#7588]
Detekt gradle plugin v1.23.6
JVM 17
Kotlin 2.0.20

Excluding Sarif output report via yaml config file does not work:

```
output-reports:
  active: true
  exclude:
   - 'SarifOutputReport'
  # - 'TxtOutputReport'
   - 'XmlOutputReport'
   - 'HtmlOutputReport'
   - 'MdOutputReport'
```

This won't exclude it, but rather create a detekt.sarif file under build/reports/detekt. The content of the file is also weird (2384 lines)
