### ISSUE TITLE
Custom rule not working running from CLI

### ISSUE THREAD

**Issue by krayneva** [detekt/detekt#8001]
I'm developing a custom rule that requires type resolution and I want to run it using CLI:
config is

```
# You can check rules description at  https://detekt.dev/exceptions.html#compliant-code
build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
......

CustomDetektRules:
  active: true
  BigDecimalRule:
    active: true

```

CLI command:
```
  OUTPUT=$(java -jar "$DETEKT_BIN" \
    --build-upon-default-config \
    --config detekt_custom.yml \
    --baseline detekt-merged-baseline.xml \
    --auto-correct \
    --input "$DETEKT_INPUT" \
    --plugins "$CUSTOM_RULES_JAR" \
    --classpath "$ANDROID_SDK_JAR" \
    --debug \
    2>&1)
```

I added path to jar with my rule in $CUSTOM_RULES_JAR  and  --classpath "$ANDROID_SDK_JAR"

## Expected Behavior
Custom rule works from CLI

## Observed Behavior
Custom rule works only after adding **--all-rules** parameter to CLI command. 
Moreover adding  --all-rules and --classpath "$ANDROID_SDK_JAR" parameters affects other (not custom) rules. 
For example: 
```
  LongMethod:
    active: true
    ignoreAnnotated:
      - 'Composable'
```
after adding classpath parameter stops ignoring methods with "@Composable" annotation. 

## Your Environment
* Version of detekt used: 1.23.8
* Version of Gradle used (if applicable): 8.9
* Operating System and version: mac OS
