### ISSUE TITLE
False positive StringLiteralDuplication

### ISSUE THREAD

**Issue by Dosexe** [detekt/detekt#8074]
## Expected Behavior

Rule `StringLiteralDuplication` should not be triggered

## Observed Behavior

Code triggers `StringLiteralDuplication` rule

## Steps to Reproduce

run `gradle detekt` over code below
```kt
object ConfigUtils {

    private val prefix = "test"

    fun createX(name: String): String = "$prefix$name"

    fun createY(name: String): String = "$prefix$name"
}
```

## Context

In my example it is clear that the strings are not the same, since the logic under different function can be different and the `name` param may mean different things and have different values in the context. If code is replaced with `prefix + name` everything works as expected, but this is undesired code style.

Rule setup
```
  StringLiteralDuplication:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    threshold: 2
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'
```

## Your Environment

* Version of detekt used:  `1.23.8`
* Version of Gradle used (if applicable):  `8.12`
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: 
* Link to your project (if it's a public repository):
